### ISSUE TITLE
Be more precise than "high trust"

### ISSUE THREAD

**Issue by jyasskin** [WICG/WebApiDevice#1]
It's not clear what the explainer means by "the applications with the highest degree of trust". That could cover cases where the user has thought really hard about a particular application and decided to trust it, or that the browser-maker has manually reviewed the application, or, as I think you mean here, that the device owner or administrator has explicitly enabled the application through enterprise policy or an equivalent mechanism.

You could instead talk about origins for which device policy has explicitly enabled these APIs. Then we don't have to ask what other things the sites are trusted to do; they're just configured to be able to read this particular data.

**Comment by reillyeon** [comment]
The comment in #3 is similar. I think the explainer should be clear that supporting these APIs outside of a managed configuration is a non-goal, unless that isn't the case. I think that would make the trust model a lot clearer to reviewers.

**Comment by Ananubis** [comment]
Thanks for the suggestion. Two paragraphs ('What is this' and 'What are trusted applications') were changed to explicitly describe that these Web APIs are only available to managed devices. (I am not sure whether 'managed' is a commen concept which can be used directly.)

Please check the changes in this [commit](https://github.com/WICG/WebApiDevice/commit/eac85816a4c8b21aaf90aa0eee25cb0be9cea789#diff-caadb38f65af0936762fb268773d4e15f53cfa4cdb038fc1dab594177ab9aa7f), and let me know if there is any further question. Thanks!

**Comment by slightlyoff** [comment]
I agree that we should, perhaps, move away from the specific language here and instead enunciate the full set of potential risks without claiming that any specific solution is ideal (or even required).

That said, having a non-normative _"this is one way a UA could do it..."_ feels like something we absolutely want in an Explainer. Bonus points for multiple potential alternative treatments!

**Comment by sbykov-g** [comment]
I replaced 'trusted' with 'managed' throughout the explainer. Alex's comment is similar to #2 , so I'll address it there.
