### ISSUE TITLE
Link to specification

### ISSUE THREAD

**Issue by jyasskin** [WICG/WebApiDevice#14]
Your [README](https://github.com/WICG/WebApiDevice/blob/main/README.md) should have a clear link to the draft spec, and probably the repository as a whole should link there from the "about" section (using the ⚙️ icon next to "about").

**Comment by Ananubis** [comment]
The README have already included two links. But the 'about' section cannot accept an URL or other format characters in the 'description'. Any good idea to solve this? Thanks!

**Comment by jyasskin** [comment]
Since there are two specs, the 'about' section's "website" field isn't enough to link to both. I'd call this fixed by #16.
