### ISSUE TITLE
Configure automatic publishing to GitHub Pages

### ISSUE THREAD

**Issue by reillyeon** [WICG/WebApiDevice#15]
The [W3C spec-prod](https://github.com/w3c/spec-prod) GitHub action can be configured to automatically compile these specification using Bikeshed and publish the HTML version to a separate `gh-pages` branch.

See [the Web Bluetooth repo](https://github.com/WebBluetoothCG/web-bluetooth/blob/main/.github/workflows/pr-push.yml) for an example of how to configure the action to build multiple documents from the same repository. Note that the current guidance is to name this file `auto-publish.yml`.

**Comment by Ananubis** [comment]
Thanks for the suggestion and the sample. The `auto-publish.yml` has been merged. The link to the draft specification works normally as well.
