### ISSUE TITLE
Suggesting 'Managed Device API' or similar naming

### ISSUE THREAD

**Issue by scheib** [WICG/WebApiDevice#3]
When reading https://github.com/WICG/WebApiDevice/blob/master/Explainer.md it seems that the most salient aspect of these APIs is that they cater to computing devices that are managed by enterprise, government, or other organizations. 

The terms "trusted applications" are used, but they are not as specific as they could be.  There will be non-manged devices that also have powerful APIs that need people to trust applications, e.g. even for geolocation, web camera, WebUSB, etc. 

The term "device" also applies to many other APIs, such as sensors for orientation, or USB connectivity to another device.

What sets the device identifier, serial number, etc apart more specifically are that they are managed by an organization.

**Comment by reillyeon** [comment]
Adding that defining this scope is important to avoid confusion with similar-sounding concepts such as "Trusted Web Activities".

**Comment by Ananubis** [comment]
Thanks for the suggestion. All places in the explainer using 'Device Web API' are replaced with 'Managed Device Web API' now for accuracy. More specific description is added in the first several paragraphs to emphasize that these APIs are not avaliable in unmanaged devices.

Please help to review again and let me know if it looks better now. Thanks again.

**Comment by reillyeon** [comment]
The explainer is looking a lot clearer. If possible can you avoid using the term "trusted applications" completely and instead refer to them as "managed applications"? The key observation is that "A managed application is granted a degree of trust by the device administrator."

**Comment by Ananubis** [comment]
> If possible can you avoid using the term "trusted applications" completely and instead refer to them as "managed applications"? The key observation is that "A managed application is granted a degree of trust by the device administrator."

I want to introduce the term 'trusted applications' instead of using 'managed applications' because they have some small difference. Please let me take the Chrome browser as an example. There are three kinds of 'managed applications'.
1. Disallowed applications
2. Allowed applications
3. Force-installed applications

Only the third one is considered as 'trusted applications' and available to these 'managed device web API' according to the current plan. I am also not using the term 'Force-installed applications' directly in the explainer because other browsers or platforms may have different definition of 'trusted applications' in the future.

**Comment by mgiuca** [comment]
I would also suggest changing the actual interface from `device` for the same reasons as above. It implies that that's where I'll be able to go to do all my device features like Bluetooth, Vibration, etc.

**Comment by Ananubis** [comment]
> I would also suggest changing the actual interface from `device` for the same reasons as above. It implies that that's where I'll be able to go to do all my device features like Bluetooth, Vibration, etc.

Yeah, this makes sense. In addition, another reviewer also pointed this out that the proposed name `navigator.device` has a conflict with another plugin: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-media-capture/.

We had some internal discussion about a proper name recently. What do you think if we propose `navigator.managed` as an alternative, considering all these APIs can be used on the managed devices only?

**Comment by miketaylr** [comment]
> What do you think if we propose `navigator.managed` as an alternative, considering all these APIs can be used on the managed devices only?

Ignoring the bikeshed of naming, this seems less risky from a webcompat POV than using `navigator.device`.

**Comment by Ananubis** [comment]
Thanks all. The interface name has been changed accordingly now.
