### ISSUE TITLE
Managed Configuration vs. Device Attributes

### ISSUE THREAD

**Issue by reillyeon** [WICG/WebApiDevice#4]
There seems to be some overlap between the type of values that can be requested as "managed configuration" vs. "device attributes". For example, in contrast to a serial number, which I assume is a property of the hardware, the "annotated asset tag" seems to be something configured by the administrator and so I don't see the difference between this and the types of configuration values that can be queried through the `getManagedConfiguration()` interface.

Is it possible to combine these two interfaces or is there a fundamental difference between the two that is important to maintain?

**Comment by Ananubis** [comment]
The biggest difference here between two is that managed configuration is bound to the application itself, meaning that there could be set different managed configuration for different apps, while "annotated asset tag" and other device attributes are set per-device.
