### ISSUE TITLE
Unable to set up Chrome Policy on Chrome OS

### ISSUE THREAD

**Issue by SeverColhonAccesa** [WICG/WebApiDevice#7]
On an Asus Chromebox 3, with Chrome OS 90 and on the DEV channel I cannot set the policies as presented in the guide.
There is no `/etc/opt/chrome/policies/managed/test_policy.json` file, neither folder path to that.

Is there a more detailed guide on how to do it?

**Comment by Ananubis** [comment]
There is none, you have create it. You have to create a folder path as well for all the non-existing folders if some are not yet present.
